version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'laravel_db'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'laravel_db'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'laravel_db'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - laravel_db:/var/lib/mysql
# Names our volume
volumes:
  laravel_db:
